import type { Email, JunkEmail, Deadline, AIInsights } from "@/types/email"

export const mockEmails: Email[] = [
  {
    id: "1",
    sender: "sarah.johnson@company.com",
    subject: "Q4 Budget Review - Action Required",
    snippet:
      "Hi team, we need to finalize the Q4 budget by Friday. Please review the attached documents and provide your feedback...",
    timestamp: "2 hours ago",
    priority: "high",
    category: "work",
    isRead: false,
    isPinned: true,
    isImportant: true,
    aiConfidence: 95,
    tags: ["urgent", "budget", "deadline"],
    hasDeadline: true,
    deadline: {
      date: "2024-01-26",
      description: "Q4 Budget Review deadline",
    },
  },
  {
    id: "2",
    sender: "notifications@bank.com",
    subject: "Your monthly statement is ready",
    snippet: "Your January statement is now available. View your account activity and download your statement...",
    timestamp: "5 hours ago",
    priority: "medium",
    category: "finance",
    isRead: false,
    isPinned: false,
    isImportant: false,
    aiConfidence: 78,
    tags: ["statement", "banking"],
  },
  {
    id: "3",
    sender: "team@project.com",
    subject: "Weekly standup meeting notes",
    snippet: "Here are the key takeaways from today's standup meeting. Sprint progress is on track...",
    timestamp: "1 day ago",
    priority: "low",
    category: "work",
    isRead: true,
    isPinned: false,
    isImportant: false,
    aiConfidence: 65,
    tags: ["meeting", "standup"],
  },
  {
    id: "4",
    sender: "client@business.com",
    subject: "Project delivery timeline update",
    snippet: "We need to discuss the updated timeline for the project delivery. Can we schedule a call this week?",
    timestamp: "3 hours ago",
    priority: "high",
    category: "work",
    isRead: false,
    isPinned: false,
    isImportant: true,
    aiConfidence: 88,
    tags: ["client", "timeline", "urgent"],
    hasDeadline: true,
    deadline: {
      date: "2024-01-28",
      description: "Schedule client call",
    },
  },
]

export const mockJunkEmails: JunkEmail[] = [
  {
    id: "j1",
    sender: "winner@lottery-scam.com",
    subject: "CONGRATULATIONS! You've won $1,000,000!!!",
    snippet: "You are the lucky winner of our international lottery! Click here to claim your prize immediately...",
    timestamp: "1 hour ago",
    priority: "low",
    category: "promotion",
    isRead: false,
    isPinned: false,
    isImportant: false,
    aiConfidence: 98,
    tags: ["scam", "lottery"],
    junkType: "scam",
    riskLevel: "high",
  },
  {
    id: "j2",
    sender: "deals@retailstore.com",
    subject: "50% OFF Everything - Limited Time!",
    snippet: "Don't miss out on our biggest sale of the year! Shop now and save on all your favorite items...",
    timestamp: "3 hours ago",
    priority: "low",
    category: "promotion",
    isRead: false,
    isPinned: false,
    isImportant: false,
    aiConfidence: 85,
    tags: ["promotion", "sale"],
    junkType: "promotion",
    riskLevel: "low",
  },
  {
    id: "j3",
    sender: "newsletter@techblog.com",
    subject: "Weekly Tech Digest - AI Trends",
    snippet: "This week in tech: Latest AI developments, startup funding news, and product launches...",
    timestamp: "1 day ago",
    priority: "low",
    category: "newsletter",
    isRead: false,
    isPinned: false,
    isImportant: false,
    aiConfidence: 72,
    tags: ["newsletter", "tech"],
    junkType: "newsletter",
    riskLevel: "low",
  },
]

export const mockDeadlines: Deadline[] = [
  {
    id: "d1",
    title: "Q4 Budget Review",
    date: "2024-01-26",
    time: "17:00",
    source: mockEmails[0],
    isCompleted: false,
    isSynced: false,
  },
  {
    id: "d2",
    title: "Client Call - Project Timeline",
    date: "2024-01-28",
    time: "14:00",
    source: mockEmails[3],
    isCompleted: false,
    isSynced: true,
  },
  {
    id: "d3",
    title: "Monthly Report Submission",
    date: "2024-01-30",
    time: "23:59",
    source: {
      id: "5",
      sender: "hr@company.com",
      subject: "Monthly report due end of January",
      snippet: "Please submit your monthly reports by January 30th...",
      timestamp: "2 days ago",
      priority: "medium",
      category: "work",
      isRead: true,
      isPinned: false,
      isImportant: false,
      aiConfidence: 80,
      tags: ["report", "deadline"],
    },
    isCompleted: false,
    isSynced: false,
  },
]

export const mockAIInsights: AIInsights = {
  importantEmailsToday: 4,
  junkMailsFiltered: 12,
  deadlinesDetected: 3,
  totalEmails: 47,
  priorityBreakdown: {
    high: 8,
    medium: 15,
    low: 24,
  },
}
